package rekisteri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.19 21:24:07 // Generated by ComTest
 *
 */
public class FrisbeegolfrekisteriTest {



  // Generated by ComTest BEGIN
  /** testLisaa48 */
  @Test
  public void testLisaa48() {    // Frisbeegolfrekisteri: 48
    Frisbeegolfrekisteri rekisteri = new Frisbeegolfrekisteri(); 
    Pelaaja make = new Pelaaja(); 
    Pelaaja pera = new Pelaaja(); 
    make.rekisteroi(); pera.rekisteroi(); 
    assertEquals("From: Frisbeegolfrekisteri line: 53", 0, rekisteri.getPelaajia()); 
    rekisteri.lisaa(make); 
    assertEquals("From: Frisbeegolfrekisteri line: 55", 1, rekisteri.getPelaajia()); 
    rekisteri.lisaa(pera); 
    assertEquals("From: Frisbeegolfrekisteri line: 57", 2, rekisteri.getPelaajia()); 
    assertEquals("From: Frisbeegolfrekisteri line: 58", make, rekisteri.annaPelaaja(0)); 
    assertEquals("From: Frisbeegolfrekisteri line: 59", pera, rekisteri.annaPelaaja(1)); 
    rekisteri.lisaa(make); 
    assertEquals("From: Frisbeegolfrekisteri line: 61", 3, rekisteri.getPelaajia()); 
  } // Generated by ComTest END
}