package rekisteri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.18 18:44:05 // Generated by ComTest
 *
 */
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi31 */
  @Test
  public void testRekisteroi31() {    // Pelaaja: 31
    Pelaaja pelaaja1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 33", 0, pelaaja1.getTunnusNro()); 
    pelaaja1.rekisteroi(); 
    pelaaja1.rekisteroi(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.rekisteroi(); 
    int num1 = pelaaja1.getTunnusNro(); 
    int num2 = pelaaja2.getTunnusNro(); 
    assertEquals("From: Pelaaja line: 40", num2, num1 + 1); 
  } // Generated by ComTest END
}