package rekisteri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.19 15:37:12 // Generated by ComTest
 *
 */
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa34 */
  @Test
  public void testLisaa34() {    // Pelaajat: 34
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja testi = new Pelaaja(); 
    Pelaaja testi2 = new Pelaaja(); 
    assertEquals("From: Pelaajat line: 38", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(testi); assertEquals("From: Pelaajat line: 39", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(testi2); assertEquals("From: Pelaajat line: 40", 2, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 41", testi, pelaajat.anna(0)); 
    assertEquals("From: Pelaajat line: 42", testi2, pelaajat.anna(1)); 
    pelaajat.lisaa(testi); assertEquals("From: Pelaajat line: 43", 3, pelaajat.getLkm()); 
    pelaajat.lisaa(testi); assertEquals("From: Pelaajat line: 44", 4, pelaajat.getLkm()); 
    pelaajat.lisaa(testi); assertEquals("From: Pelaajat line: 45", 5, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm57 */
  @Test
  public void testGetLkm57() {    // Pelaajat: 57
    Pelaajat pelaajat = new Pelaajat(); 
    assertEquals("From: Pelaajat line: 59", 0, pelaajat.getLkm()); 
    Pelaaja lisays = new Pelaaja(); 
    Pelaaja toinen = new Pelaaja(); 
    pelaajat.lisaa(lisays); 
    assertEquals("From: Pelaajat line: 63", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(toinen); 
    assertEquals("From: Pelaajat line: 65", 2, pelaajat.getLkm()); 
  } // Generated by ComTest END
}