package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.12 21:22:35 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi44 */
  @Test
  public void testRekisteroi44() {    // Pelaaja: 44
    Pelaaja pelaaja1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 46", 0, pelaaja1.getTunnusNro()); 
    pelaaja1.rekisteroi(); 
    pelaaja1.rekisteroi(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.rekisteroi(); 
    int num1 = pelaaja1.getTunnusNro(); 
    int num2 = pelaaja2.getTunnusNro(); 
    assertEquals("From: Pelaaja line: 53", num2, num1 + 1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse262 */
  @Test
  public void testParse262() {    // Pelaaja: 262
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse(" 2  |    Testi Pelaaja |  198"); 
    assertEquals("From: Pelaaja line: 265", 2, pelaaja.getTunnusNro()); 
    assertEquals("From: Pelaaja line: 266", true, pelaaja.toString().startsWith("2|Testi Pelaaja|198|")); 
    pelaaja.rekisteroi(); 
    int n = pelaaja.getTunnusNro(); 
    pelaaja.parse(""+(n+20)); 
    pelaaja.rekisteroi(); 
    assertEquals("From: Pelaaja line: 272", n+20+1, pelaaja.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString292 */
  @Test
  public void testToString292() {    // Pelaaja: 292
    Pelaaja pelaaja= new Pelaaja(); 
    pelaaja.parse(" 2   | Testi Pelaaja     |  123"); 
    assertEquals("From: Pelaaja line: 295", true, pelaaja.toString().startsWith("2|Testi Pelaaja|123|")); 
  } // Generated by ComTest END
}