package rekisteri.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.13 01:59:27 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa48 */
  @Test
  public void testLisaa48() {    // Pelaajat: 48
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja testi = new Pelaaja(); 
    Pelaaja testi2 = new Pelaaja(); 
    assertEquals("From: Pelaajat line: 52", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(testi); assertEquals("From: Pelaajat line: 53", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(testi2); assertEquals("From: Pelaajat line: 54", 2, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 55", testi, pelaajat.anna(0)); 
    assertEquals("From: Pelaajat line: 56", testi2, pelaajat.anna(1)); 
    pelaajat.lisaa(testi); assertEquals("From: Pelaajat line: 57", 3, pelaajat.getLkm()); 
    pelaajat.lisaa(testi); assertEquals("From: Pelaajat line: 58", 4, pelaajat.getLkm()); 
    pelaajat.lisaa(testi); assertEquals("From: Pelaajat line: 59", 5, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi126 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi126() throws SailoException {    // Pelaajat: 126
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(); pelaaja1.parse("1|Jouni Ogeli|123|340|"); 
    Pelaaja pelaaja2 = new Pelaaja(); pelaaja2.parse("2|Omra Jatka|321|452|"); 
    Pelaaja pelaaja3 = new Pelaaja(); pelaaja3.parse("3|Osom Mattsby|23|10|"); 
    Pelaaja pelaaja4 = new Pelaaja(); pelaaja4.parse("4|Fyrer Maltsu|300|350|"); 
    Pelaaja pelaaja5 = new Pelaaja(); pelaaja5.parse("5|Kiwi Fruitti|170|780|"); 
    pelaajat.lisaa(pelaaja1); pelaajat.lisaa(pelaaja2); pelaajat.lisaa(pelaaja3); 
    pelaajat.lisaa(pelaaja4); pelaajat.lisaa(pelaaja5); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm149 */
  @Test
  public void testGetLkm149() {    // Pelaajat: 149
    Pelaajat pelaajat = new Pelaajat(); 
    assertEquals("From: Pelaajat line: 151", 0, pelaajat.getLkm()); 
    Pelaaja lisays = new Pelaaja(); 
    Pelaaja toinen = new Pelaaja(); 
    pelaajat.lisaa(lisays); 
    assertEquals("From: Pelaajat line: 155", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(toinen); 
    assertEquals("From: Pelaajat line: 157", 2, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta212 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta212() throws SailoException {    // Pelaajat: 212
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(); Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja1.taytaTestiTiedot(); 
    pelaaja2.taytaTestiTiedot(); 
    String hakemisto = "testipelaajat"; 
    String tiedNimi = hakemisto+"/pelaajat"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    pelaajat.lueTiedostosta(tiedNimi); 
    fail("Pelaajat: 227 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    pelaajat.lisaa(pelaaja1); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.tallenna(); 
    pelaajat = new Pelaajat(); 
    pelaajat.lueTiedostosta(tiedNimi); 
    Iterator<Pelaaja> i = pelaajat.iterator(); 
    assertEquals("From: Pelaajat line: 234", pelaaja1, i.next()); 
    assertEquals("From: Pelaajat line: 235", pelaaja2, i.next()); 
    assertEquals("From: Pelaajat line: 236", false, i.hasNext()); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.tallenna(); 
    assertEquals("From: Pelaajat line: 239", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Pelaajat line: 241", true, fbak.delete()); 
    assertEquals("From: Pelaajat line: 242", true, dir.delete()); 
  } // Generated by ComTest END
}